import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./Header/header";
import Footer from "./Header/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "RMDB",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-black min-h-screen">
      <body className={inter.className}><Header />{children}<Footer /></body>
    </html>
  );
}
